import React from 'react';
// All icons are now sourced from lucide-react and re-exported
// This keeps icon imports consistent across the app.
export { 
    Dumbbell as DumbbellIcon,
    Menu as MenuIcon,
    X as XIcon,
    Facebook as FacebookIcon,
    Instagram as InstagramIcon,
    Twitter as TwitterIcon,
    Users as UsersIcon,
    Bolt as BoltIcon,
    Clipboard as ClipboardIcon,
    Sparkles as SparklesIcon,
    Globe as GlobeIcon,
    ChevronDown as ChevronDownIcon,
    MapPin as MapPinIcon,
    Phone as PhoneIcon,
    Mail as MailIcon,
    CheckCircle as CheckCircleIcon,
    ArrowRight as ArrowRightIcon,
    Pin as PinIcon,
    ChevronLeft as ChevronLeftIcon,
    ChevronRight as ChevronRightIcon,
    RefreshCw as RefreshIcon,
    Pencil as PencilIcon,
    Trash as TrashIcon,
    ArrowUp as ScaleUpIcon,
    ArrowDown as ScaleDownIcon,
    Sun as SunIcon,
    Moon as MoonIcon,
    CalendarCheck as CalendarCheckIcon,
} from 'lucide-react';
